SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY, A.AUTHOR_NAME

ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;