SELECT G3.ID
FROM ECOLI_DATA G1             -- 1세대
JOIN ECOLI_DATA G2 ON G1.ID = G2.PARENT_ID -- 2세대 
JOIN ECOLI_DATA G3 ON G2.ID = G3.PARENT_ID -- 3세대
WHERE G1.PARENT_ID IS NULL     -- 1세대는 반드시 최상위 부모여야 함
ORDER BY G3.ID;