SELECT 
    P.PRODUCT_CODE, 
    SUM(P.PRICE * S.SALES_AMOUNT) AS SALES -- 상품별 총 매출액 합계
FROM PRODUCT P
JOIN OFFLINE_SALE S USING(PRODUCT_ID)
GROUP BY P.PRODUCT_CODE -- 상품코드별로 묶기
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;