WITH CAR_DATA AS ( -- 세단,SUV,대여가능
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
      AND CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-11-30' 
            AND END_DATE >= '2022-11-01'
      )
)
SELECT C.CAR_ID,C.CAR_TYPE, (C.DAILY_FEE*(1-P.DISCOUNT_RATE/100)*30)AS FEE
FROM(SELECT * FROM CAR_DATA) C
JOIN (SELECT CAR_TYPE,REPLACE(DISCOUNT_RATE,'%','') AS DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE LIKE '30%') P USING(CAR_TYPE)
HAVING FEE BETWEEN '500000' AND '2000000'
ORDER BY FEE DESC, C.CAR_TYPE,C.CAR_ID DESC;