SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P 
JOIN FOOD_ORDER O USING(PRODUCT_ID)
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY O.PRODUCT_ID
-- 같은 메뉴가 여러개 주문됐을 때 항상 고려하기
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;