-- 코드를 작성해주세요
-- A->B 순이면 TREE 테이블에 ITEM_ID가B, PARENT_ITEM_ID가A임. 희귀도가 RARE인 아이템의 다음 업그레이드 찾기
SELECT I.ITEM_ID,I.ITEM_NAME,I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I ON T.ITEM_ID=I.ITEM_ID
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID=P.ITEM_ID
WHERE P.RARITY='RARE'
ORDER BY ITEM_ID DESC;
