SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)M
ON I.FISH_TYPE=M.FISH_TYPE
AND I.LENGTH=M.MAX_LEN
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE=I.FISH_TYPE
ORDER BY I.ID